openapi: 3.0.0
info:
  version: 0.1.0
  title: Nicen
  description: A source code formatter
paths:
  /:
    post:
      summary: Reformat code
      description: ''
      operationId: reformat
      responses:
        '400':
          description: Invalid input
          schema: '#/components/schemas/Error'
        '200':
          description: Reformatted code
          schema: '#/components/schemas/ReformatResponse'
      requestBody:
        $ref: '#/components/requestBodies/ReformatBody'
components:
  schemas:
    ReformatRequest:
      type: object
      properties:
        width:
          type: integer
          format: int64
          default: 120
        handler:
          type: string
        language:
          type: string
          required: true
        content:
          type: string
          required: true
    ReformatResponse:
      type: object
      properties:
        content:
          type: string
        language:
          type: string
        handler:
          type: string
        time:
          type: integer
    Error:
      type: object
      properties:
        error:
          type: string
  requestBodies:
    ReformatBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReformatRequest'
        application/x-www-form-urlencoded:
          schema:
            $ref: '#/components/schemas/ReformatRequest'
      required: true
